SOGoProfileURL: "postgresql://sogo:sogo@test-postgres:5432/sogo/sogo_user_profile"
OCSFolderInfoURL: "postgresql://sogo:sogo@test-postgres:5432/sogo/sogo_folder_info"
OCSSessionsFolderURL: "postgresql://sogo:sogo@test-postgres:5432/sogo/sogo_sessions_folder"
OCSAdminURL: "postgresql://sogo:sogo@test-postgres:5432/sogo/sogo_admin"

SOGoPasswordChangeEnabled: true
SOGoUserSources: 
  - type: sql
    id: directory
    viewURL: "postgresql://sogo:sogo@test-postgres:5432/sogo/sogo_view"
    canAuthenticate: true
    isAddressBook: true
    userPasswordAlgorithm: md5

SOGoPageTitle: SOGo
SOGoVacationEnabled: true
SOGoForwardEnabled: true
SOGoSieveScriptsEnabled: true
SOGoMailAuxiliaryUserAccountsEnabled: true
SOGoTrustProxyAuthentication: false
SOGoXSRFValidationEnabled: false

SOGoLanguage: English
SOGoTimeZone: America/Montreal

SOGoDebugRequests: true
SoDebugBaseURL: true
ImapDebugEnabled: true
LDAPDebugEnabled: true
PGDebugEnabled: true
MySQL4DebugEnabled: true
SOGoUIxDebugEnabled: true
WODontZipResponse: true