apiVersion: v2
name: sogo
version: 0.1.10
description: A helm chart for the docker-sogo docker image
type: application
keywords:
- sogo
- alinto
- inverse
- mail
- calendar
home: https://github.com/sonroyaalmerol/docker-sogo
sources:
- https://github.com/sonroyaalmerol/docker-sogo
maintainers:
- name: Son Roy Almerol
  email: sogo@snry.me
  url: https://github.com/sonroyaalmerol
icon: https://www.sogo.nu/img/sogo.svg
appVersion: 5.10.0
deprecated: false
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: GitHub source
      url: https://github.com/sonroyaalmerol/docker-sogo/
  artifacthub.io/images: |
    - name: docker-sogo
      image: sonroyaalmerol/docker-sogo:5.10.0-2
  artifacthub.io/screenshots: |
    - title: SOGo
      url: https://www.sogo.nu/img/screenshot.png
dependencies:
  - name: postgresql
    version: 15.3.*
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: mariadb
    version: 18.0.*
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mariadb.enabled
  - name: memcached
    version: 7.0.*
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: memcached.enabled
