sogo:
  configs:
    SOGoPageTitle: SOGo
    SOGoVacationEnabled: true
    SOGoForwardEnabled: true
    SOGoSieveScriptsEnabled: true
    SOGoMailAuxiliaryUserAccountsEnabled: true
    SOGoTrustProxyAuthentication: false
    SOGoXSRFValidationEnabled: false
    SOGoLanguage: English
    SOGoTimeZone: America/Montreal
    WOWorkersCount: 5
mariadb:
  enabled: true
  auth:
    database: sogo
    username: sogo
    password: changeme
  architecture: standalone
  primary:
    persistence:
      enabled: false
memcached:
  enabled: true
