useTestResourcesDev:
  database: true
sogo:
  configs:
    SOGoPageTitle: SOGo
    SOGoVacationEnabled: true
    SOGoForwardEnabled: true
    SOGoSieveScriptsEnabled: true
    SOGoMailAuxiliaryUserAccountsEnabled: true
    SOGoTrustProxyAuthentication: false
    SOGoXSRFValidationEnabled: false
    SOGoLanguage: English
    SOGoTimeZone: America/Montreal
    WOWorkersCount: 5
  secrets:
    SOGoProfileURL: postgresql://postgres:test123@test-postgres:5432/sogo/sogo_user_profile
    OCSFolderInfoURL: postgresql://postgres:test123@test-postgres:5432/sogo/sogo_folder_info
    OCSSessionsFolderURL: postgresql://postgres:test123@test-postgres:5432/sogo/sogo_sessions_folder
    OCSAdminURL: postgresql://postgres:test123@test-postgres:5432/sogo/sogo_admin
