{{- if or .Values.mariadb.enabled .Values.postgresql.enabled .Values.sogo.configs.OCSFolderInfoURL }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sogo.fullname" . }}-db
  labels:
    app.kubernetes.io/name: {{ include "sogo.name" . }}
    helm.sh/chart: {{ include "sogo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.sogo.configs.OCSFolderInfoURL }}
  db-username: {{ include "sogo.db.parsed.username" . | b64enc | quote }}
  db-password: {{ include "sogo.db.parsed.password" . | b64enc | quote }}
  {{- else if .Values.mariadb.enabled }}
  db-username: {{ .Values.mariadb.auth.username | b64enc | quote }}
  db-password: {{ .Values.mariadb.auth.password | b64enc | quote }}
  {{- else if .Values.postgresql.enabled }}
  db-username: {{ .Values.postgresql.global.postgresql.auth.username | b64enc | quote }}
  db-password: {{ .Values.postgresql.global.postgresql.auth.password | b64enc | quote }}
  {{- end }}
{{- end }}