---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sogo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sogo.name" . }}
    helm.sh/chart: {{ include "sogo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: app
    {{- with .Values.deploymentLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    {{- toYaml .Values.sogo.strategy | nindent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sogo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sogo.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: app
        {{- if .Values.memcached.enabled }}
        {{ template "sogo.memcached.fullname" . }}-client: "true"
        {{- end }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        sogo-config-hash: {{ print (toJson .Values.sogo.configs) | sha256sum }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . }}
        {{- end}}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "sogo.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.lifecycle }}
          lifecycle:
            {{- with .postStartCommand }}
            postStart:
              exec:
                command:
                  {{- toYaml . | nindent 18 }}
            {{- end }}
            {{- with .preStopCommand }}
            preStop:
              exec:
                command:
                  {{- toYaml . | nindent 18 }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.sogo.containerPort }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          {{- if .enabled }}
          livenessProbe:
            httpGet:
              path: /SOGo
              port:  {{ $.Values.sogo.containerPort }}
              httpHeaders:
              - name: Host
                value: {{ $.Values.sogo.host | quote }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            successThreshold: {{ .successThreshold }}
            failureThreshold: {{ .failureThreshold }}
          {{- end }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          {{- if .enabled }}
          readinessProbe:
            httpGet:
              path: /SOGo
              port:  {{ $.Values.sogo.containerPort }}
              httpHeaders:
              - name: Host
                value: {{ $.Values.sogo.host | quote }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            successThreshold: {{ .successThreshold }}
            failureThreshold: {{ .failureThreshold }}
          {{- end }}
          {{- end }}
          {{- with .Values.startupProbe }}
          {{- if .enabled }}
          startupProbe:
            httpGet:
              path: /SOGo
              port:  {{ $.Values.sogo.containerPort }}
              httpHeaders:
              - name: Host
                value: {{ $.Values.sogo.host | quote }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            successThreshold: {{ .successThreshold }}
            failureThreshold: {{ .failureThreshold }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.sogo.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- include "sogo.volumeMounts" . | trim | nindent 12 }}
            {{- if .Values.sogo.configs }}
            - name: sogo-configs
              mountPath: /etc/sogo/sogo.conf.d/99-helm.yaml
              subPath: configs
              readOnly: true
            {{- end }}
            {{- if .Values.sogo.secrets }}
            - name: sogo-secrets
              mountPath: /etc/sogo/sogo.conf.d/99-secrets.yaml
              subPath: secrets
              readOnly: true
            {{- end }}
        {{- with .Values.sogo.extraSidecarContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.sogo.extraInitContainers }}
      initContainers:
        {{- with .Values.sogo.extraInitContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}{{/* end-if any initContainer */}}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.sogo.configs }}
        - name: sogo-configs
          configMap:
            name: {{ template "sogo.fullname" . }}-config
        {{- end }}
        {{- if .Values.sogo.secrets }}
        - name: sogo-secrets
          secret:
            secretName: {{ template "sogo.fullname" . }}-secret
        {{- end }}
        {{- with .Values.sogo.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      securityContext:
        {{- with .Values.securityContext }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.sogo.podSecurityContext }}
        {{- toYaml . | nindent 8 }}
        {{- else }}
        # Will mount configuration files as www-data (id: 33) for sogo
        fsGroup: 33
        {{- end }}{{/* end-with podSecurityContext */}}
      {{- if .Values.rbac.enabled }}
      serviceAccountName: {{ .Values.rbac.serviceaccount.name }}
      {{- end }}
