{{- if .Values.sogo.emailAlarms -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sogo.fullname" . }}-email-alarms-cron
  labels:
    app.kubernetes.io/name: {{ include "sogo.name" . }}
    helm.sh/chart: {{ include "sogo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- if or .Values.sogo.smtp.username .Values.sogo.smtp.existingSecret }}
  cron: {{ printf "* * * * *  sogo	/usr/sbin/sogo-ealarms-notify -p /etc/sogo/smtp.creds > /dev/null 2>&1" | squote }}
{{- else }}
  cron: {{ printf "* * * * *  sogo	/usr/sbin/sogo-ealarms-notify > /dev/null 2>&1" | squote }}
{{- end }}
