{{- if .Values.hpa.enabled }}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "sogo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sogo.name" . }}
    helm.sh/chart: {{ include "sogo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: app
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: {{ template "sogo.fullname" . }}
  {{- with .Values.hpa }}
  minReplicas: {{ .minPods }}
  maxReplicas: {{ .maxPods }}
  targetCPUUtilizationPercentage: {{ .cputhreshold }}
  {{- end }}{{/* end-with .hpa */}}
{{- end }}
