{{- if .Values.sogo.sessionCleanup -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sogo.fullname" . }}-oidc-cron
  labels:
    app.kubernetes.io/name: {{ include "sogo.name" . }}
    helm.sh/chart: {{ include "sogo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  cron: '* * * * * /usr/sbin/sogo-tool clean-openid-sessions > /dev/null 2>&1'
{{- end }}
