{{- if .Values.sogo.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sogo.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "sogo.name" . }}
    helm.sh/chart: {{ include "sogo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  secrets: {{ .Values.sogo.secrets | toYaml | b64enc }}
{{- end }}
