{{- if .Values.sogo.sessionCleanup -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sogo.fullname" . }}-session-cron
  labels:
    app.kubernetes.io/name: {{ include "sogo.name" . }}
    helm.sh/chart: {{ include "sogo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  cron: {{ (printf "* * * * * sogo  /usr/sbin/sogo-tool expire-sessions %d > /dev/null 2>&1" (.Values.sogo.sessionCleanup.maxInactivity | int)) | squote }}
{{- end }}
