{{- if and .Values.sogo.vacationExpiration.enabled (not .Values.sogo.vacationExpiration.sieve.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sogo.fullname" . }}-sieve-creds
  labels:
    app.kubernetes.io/name: {{ include "sogo.name" . }}
    helm.sh/chart: {{ include "sogo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.sogo.vacationExpiration.sieve }}
  creds: {{ printf "%s:%s" .Values.sogo.vacationExpiration.sieve.username .Values.sogo.vacationExpiration.sieve.password | b64enc | quote }}
{{- end }}
{{- end }}