{{- if and .Values.sogo.emailAlarms.enabled (not .Values.sogo.emailAlarms.smtp.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sogo.fullname" . }}-smtp-creds
  labels:
    app.kubernetes.io/name: {{ include "sogo.name" . }}
    helm.sh/chart: {{ include "sogo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.sogo.emailAlarms.smtp }}
  creds: {{ printf "%s:%s" .Values.sogo.emailAlarms.smtp.username .Values.sogo.emailAlarms.smtp.password | b64enc | quote }}
{{- end }}
{{- end }}