---
name: Release image
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  release:
    name: Release - Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Get latest version of SOGo
        id: sogo
        run: |
          echo "VERSION=$(curl -s https://api.github.com/repos/Alinto/sogo/releases/latest | jq -r '.tag_name' | sed 's/SOGo-//')" >> "$GITHUB_OUTPUT"

      - name: Get latest version of Docker image
        id: image
        run: |
          echo "VERSION=$(curl -s https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest | jq -r '.tag_name')" >> "$GITHUB_OUTPUT"

      - name: Checkout
        if: steps.sogo.outputs.VERSION != steps.image.outputs.VERSION
        uses: actions/checkout@v4

      - name: Docker - Login
        if: steps.sogo.outputs.VERSION != steps.image.outputs.VERSION
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker - GHCR Login
        if: steps.sogo.outputs.VERSION != steps.image.outputs.VERSION
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        if: steps.sogo.outputs.VERSION != steps.image.outputs.VERSION
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: steps.sogo.outputs.VERSION != steps.image.outputs.VERSION
        uses: docker/setup-buildx-action@v3

      - name: Docker - Metadata
        if: steps.sogo.outputs.VERSION != steps.image.outputs.VERSION
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=${{ steps.sogo.outputs.VERSION }}
          flavor: latest=true

      - name: Docker - Build / Push
        if: steps.sogo.outputs.VERSION != steps.image.outputs.VERSION
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            SOGO_VERSION=${{ steps.sogo.outputs.VERSION }}

      - name: Github Release
        uses: softprops/action-gh-release@v2
        if: steps.sogo.outputs.VERSION != steps.image.outputs.VERSION
        with:
          tag_name: ${{ steps.sogo.outputs.VERSION }}
          make_latest: 'true'
          body: |
            SOGo Update: https://github.com/Alinto/sogo/releases/tag/SOGo-${{ steps.sogo.outputs.VERSION }}